# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

# Same as ant-push.yml, except that no SonarCloud scan is done since pull
# requests do not have access to repository secrets (and thus generate an error
# when attempting to use Sonar).

name: Build (pull request)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # Remove 'pom.xml' otherwise Sonar will fail forcing to use Maven
    - name: Remove pom.xml
      run: rm -f pom.xml
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Test with JUnit
      run: ant -noinput -buildfile build.xml test
    - name: Test with JUnit
      run: ant -noinput -buildfile build.xml report
